# Generated by Django 5.1.7 on 2025-04-09 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс 64 символів', max_length=64, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Макс 255 символів', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('audio_file', models.FileField(upload_to='beats/', verbose_name='Аудіо-файл')),
                ('demo_file', models.FileField(blank=True, null=True, upload_to='demos/', verbose_name='Демо-файл')),
                ('cover_image', models.ImageField(default='images/default.png', upload_to='covers/', verbose_name='Обкладинка')),
                ('slug', models.SlugField(unique_for_date=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації'), verbose_name='Слаг')),
                ('tag', models.ManyToManyField(blank=True, to='main.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Біт',
                'verbose_name_plural': 'Біти',
                'ordering': ['-pub_date'],
            },
        ),
    ]
