# Generated by Django 5.1.7 on 2025-04-09 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_beat_options_remove_beat_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beat',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Біт', 'verbose_name_plural': 'Біти'},
        ),
        migrations.RenameField(
            model_name='beat',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='beat',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації'),
        ),
    ]
