# Generated by Django 5.1.7 on 2025-04-18 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_beat_options_rename_tag_beat_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ціна'),
        ),
    ]
