# Generated by Django 5.1.7 on 2025-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_beat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='author',
            field=models.CharField(default='Unknown', help_text='Макс 64 символа', max_length=64, verbose_name='Автор'),
        ),
    ]
