# Generated by Django 5.1.7 on 2025-04-19 09:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_beat_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='cover_image',
            field=models.ImageField(default='img/default.png', upload_to='covers/', verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ціна'),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Макс 255 символів', max_length=255, verbose_name='Назва набору')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('cover_image', models.ImageField(default='img/default.png', upload_to='kits/covers/', verbose_name='Обкладинка')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ціна')),
                ('author', models.CharField(default='Unknown', help_text='Макс 64 символа', max_length=64, verbose_name='Автор')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('license_info', models.TextField(blank=True, verbose_name='Інформація про ліцензію')),
                ('tags', models.ManyToManyField(blank=True, to='main.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Кіт',
                'verbose_name_plural': 'Кіти',
                'ordering': ['-pub_date'],
            },
        ),
    ]
