# Generated by Django 5.1.7 on 2025-04-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_beat_cover_image_alter_beat_price_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='file',
            field=models.FileField(default='kits/files/icon.7z', upload_to='kits/files/', verbose_name='Файли набору (ZIP)'),
        ),
    ]
