# Generated by Django 5.1.7 on 2025-04-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_beat_premium_price_kit_premium_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='premium_price',
        ),
    ]
