# Generated by Django 5.1.7 on 2025-04-22 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_beat_premium_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Преміум ціна'),
        ),
    ]
