# Generated by Django 5.1.7 on 2025-04-30 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_beat_premium_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='cover_image',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to='covers/', verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
    ]
