# Generated by Django 5.1.7 on 2025-04-30 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_beat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації'),
        ),
    ]
