# Generated by Django 5.1.7 on 2025-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_beat_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beat',
            options={},
        ),
        migrations.AlterField(
            model_name='beat',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
