# Generated by Django 5.1.7 on 2025-04-30 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_beat_options_alter_beat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публікації'),
        ),
    ]
